//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace UFC
{
    public partial class COMPROVANTE
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual System.DateTime DATA
        {
            get;
            set;
        }
    
        public virtual string TIPO
        {
            get;
            set;
        }
    
        public virtual double VALOR
        {
            get;
            set;
        }
    
        public virtual System.Guid IDUSUARIO
        {
            get { return _iDUSUARIO; }
            set
            {
                if (_iDUSUARIO != value)
                {
                    if (Usuario != null && Usuario.Id != value)
                    {
                        Usuario = null;
                    }
                    _iDUSUARIO = value;
                }
            }
        }
        private System.Guid _iDUSUARIO;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<APOSTA> APOSTA
        {
            get
            {
                if (_aPOSTA == null)
                {
                    var newCollection = new FixupCollection<APOSTA>();
                    newCollection.CollectionChanged += FixupAPOSTA;
                    _aPOSTA = newCollection;
                }
                return _aPOSTA;
            }
            set
            {
                if (!ReferenceEquals(_aPOSTA, value))
                {
                    var previousValue = _aPOSTA as FixupCollection<APOSTA>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAPOSTA;
                    }
                    _aPOSTA = value;
                    var newValue = value as FixupCollection<APOSTA>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAPOSTA;
                    }
                }
            }
        }
        private ICollection<APOSTA> _aPOSTA;
    
        public virtual Usuario Usuario
        {
            get { return _usuario; }
            set
            {
                if (!ReferenceEquals(_usuario, value))
                {
                    var previousValue = _usuario;
                    _usuario = value;
                    FixupUsuario(previousValue);
                }
            }
        }
        private Usuario _usuario;

        #endregion
        #region Association Fixup
    
        private void FixupUsuario(Usuario previousValue)
        {
            if (previousValue != null && previousValue.COMPROVANTE.Contains(this))
            {
                previousValue.COMPROVANTE.Remove(this);
            }
    
            if (Usuario != null)
            {
                if (!Usuario.COMPROVANTE.Contains(this))
                {
                    Usuario.COMPROVANTE.Add(this);
                }
                if (IDUSUARIO != Usuario.Id)
                {
                    IDUSUARIO = Usuario.Id;
                }
            }
        }
    
        private void FixupAPOSTA(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (APOSTA item in e.NewItems)
                {
                    item.COMPROVANTE = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (APOSTA item in e.OldItems)
                {
                    if (ReferenceEquals(item.COMPROVANTE, this))
                    {
                        item.COMPROVANTE = null;
                    }
                }
            }
        }

        #endregion
    }
}
