//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace UFC
{
    public partial class EVENTO
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string NOME
        {
            get;
            set;
        }
    
        public virtual string TITULO
        {
            get;
            set;
        }
    
        public virtual System.DateTime DATA
        {
            get;
            set;
        }
    
        public virtual bool LIBERADO
        {
            get;
            set;
        }
    
        public virtual double VALOR
        {
            get;
            set;
        }
    
        public virtual string CAMINHO_POSTER
        {
            get;
            set;
        }
    
        public virtual bool MULTIPLASAPOSTAS
        {
            get;
            set;
        }
    
        public virtual bool RESULTADODISPONIVEL
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<LUTA> LUTA
        {
            get
            {
                if (_lUTA == null)
                {
                    var newCollection = new FixupCollection<LUTA>();
                    newCollection.CollectionChanged += FixupLUTA;
                    _lUTA = newCollection;
                }
                return _lUTA;
            }
            set
            {
                if (!ReferenceEquals(_lUTA, value))
                {
                    var previousValue = _lUTA as FixupCollection<LUTA>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLUTA;
                    }
                    _lUTA = value;
                    var newValue = value as FixupCollection<LUTA>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLUTA;
                    }
                }
            }
        }
        private ICollection<LUTA> _lUTA;

        #endregion
        #region Association Fixup
    
        private void FixupLUTA(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (LUTA item in e.NewItems)
                {
                    item.EVENTO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (LUTA item in e.OldItems)
                {
                    if (ReferenceEquals(item.EVENTO, this))
                    {
                        item.EVENTO = null;
                    }
                }
            }
        }

        #endregion
    }
}
