//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace UFC
{
    public partial class PATROCINIO
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string CAMINHOBANNER
        {
            get;
            set;
        }
    
        public virtual string PREMIO
        {
            get;
            set;
        }
    
        public virtual double VALOR
        {
            get;
            set;
        }
    
        public virtual int IDEVENTO
        {
            get;
            set;
        }
    
        public virtual string PATROCINADOR
        {
            get;
            set;
        }
    
        public virtual string LINKBANNER
        {
            get;
            set;
        }

        #endregion
    }
}
