//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace UFC
{
    public partial class RESULTADO
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> IDCOMPROVANTE
        {
            get;
            set;
        }
    
        public virtual System.DateTime DATAAPOSTA
        {
            get;
            set;
        }
    
        public virtual string NOME
        {
            get;
            set;
        }
    
        public virtual int PONTUACAO
        {
            get;
            set;
        }
    
        public virtual string OBSERVACAO
        {
            get;
            set;
        }
    
        public virtual int IDEVENTO
        {
            get;
            set;
        }

        #endregion
    }
}
